### ISSUE TITLE
train:ImportError: dynamic module does not define module export function (PyInit__roi_crop)

### ISSUE THREAD

**Issue by emmra** [guoruoqian/DetNet_pytorch#13]
With using the version of pytorch0.3.1 and pytorch0.4.0 both with python3.6,  I met the error as blow:

Traceback (most recent call last):
  File "trainval_aiia.py", line 29, in <module>
    from model.utils.net_utils import vis_detections
  File "/disk1/g201708021059/gg/DetNet_Pytorch/lib/model/utils/net_utils.py", line 11, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/disk1/g201708021059/gg/DetNet_Pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/disk1/g201708021059/gg/DetNet_Pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: dynamic module does not define module export function (PyInit__roi_crop)

When I change to use python2.7,pytorch0.3.1,other error arised as blow:

(py27-pytorch) g201708021059@scw4750:~/gg/DetNet_Pytorch$ CUDA_VISIBLE_DEVICES=0 python3 trainval_aiia.py exp_name --dataset pascal_voc --net detnet59 --bs 1 --nw 1 --lr 1e-3 --epochs 12 --save_dir weights --cuda --use_tfboard True
Traceback (most recent call last):
  File "trainval_aiia.py", line 29, in <module>
    from model.utils.net_utils import vis_detections
  File "/disk1/g201708021059/gg/DetNet_Pytorch/lib/model/utils/net_utils.py", line 9, in <module>
    import torchvision.models as models
ModuleNotFoundError: No module named 'torchvision.models'

and I have done the complilation process, with using the cuda80/cudnn6.0

**Comment by SteinsGate9** [comment]
same error~

**Comment by gaichengyuan** [comment]
@emmra Have you solved this problem? I made the same bug as you.
