### ISSUE TITLE
Train on my own data:  ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by emmra** [guoruoqian/DetNet_pytorch#15]
I use cuda90/cudnn7.pytorch 0.3.1.Someone adding env.close() or env.env.close() at the end of programs wokes. but i adding it the end of trainval_net.py doesn't work. Can anyone tell me why?

Traceback (most recent call last):
  File "trainval_aiia.py", line 362, in <module>
    roi_labels = FPN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk2/gg/DetNet_Pytorch/lib/model/fpn/fpn.py", line 254, in forward
    bbox_pred_select = torch.gather(bbox_pred_view, 1, rois_label.long().view(rois_label.size(0), 1, 1).expand(rois_label.size(0), 1, 4))
RuntimeError: invalid argument 2: Input tensor must have same size as output tensor apart from the specified dimension at /pytorch/torch/lib/THC/generic/THCTensorScatterGather.cu:29
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7fbe91f657f0>>
Traceback (most recent call last):
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 333, in __del__
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/multiprocessing/queues.py", line 344, in get
ImportError: sys.meta_path is None, Python is likely shutting down

When i run trainval_net.py by my data like voc the other error arised as blow.....please help me....

Traceback (most recent call last):
  File "trainval_aiia.py", line 362, in <module>
    roi_labels = FPN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk2/gg/DetNet_Pytorch/lib/model/fpn/fpn.py", line 192, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(rpn_feature_maps, im_info, gt_boxes, num_boxes)
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk2/gg/DetNet_Pytorch/lib/model/rpn/rpn_fpn.py", line 109, in forward
    rpn_data = self.RPN_anchor_target((rpn_cls_score_alls.data, gt_boxes, im_info, num_boxes, rpn_shapes))
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/disk2/gg/DetNet_Pytorch/lib/model/rpn/anchor_target_layer_fpn.py", line 141, in forward
    positive_weights = 1.0 / num_examples
  File "/home/disk2/anaconda3/envs/tf/lib/python3.6/site-packages/torch/tensor.py", line 320, in __rdiv__
    return self.reciprocal() * other
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensor

**Comment by emmra** [comment]
I use cuda90/cudnn7.pytorch 0.3.1.Someone adding env.close() or env.env.close() at the end of programs wokes. but i adding it at the end of trainval_net.py doesn't work. Can anyone tell me why?

**Comment by emmra** [comment]
I solve this problem by cleaning data.so I close
