### ISSUE TITLE
A problem with soft_nms

### ISSUE THREAD

**Issue by WangTianYuan** [guoruoqian/DetNet_pytorch#20]
`Traceback (most recent call last):
  File "trainval_net.py", line 36, in <module>
    from model.fpn.detnet_backbone import detnet
  File "/home/wty/project/DetNet_pytorch/lib/model/fpn/detnet_backbone.py", line 6, in <module>
    from model.fpn.fpn import _FPN
  File "/home/wty/project/DetNet_pytorch/lib/model/fpn/fpn.py", line 12, in <module>
    from model.rpn.rpn_fpn import _RPN_FPN
  File "/home/wty/project/DetNet_pytorch/lib/model/rpn/rpn_fpn.py", line 7, in <module>
    from .proposal_layer_fpn import _ProposalLayer_FPN
  File "/home/wty/project/DetNet_pytorch/lib/model/rpn/proposal_layer_fpn.py", line 19, in <module>
    from model.nms.nms_wrapper import nms
  File "/home/wty/project/DetNet_pytorch/lib/model/nms/nms_wrapper.py", line 10, in <module>
    from model.nms.cpu_nms import cpu_soft_nms

ModuleNotFoundError: No module named 'model.nms.cpu_nms'`
I have installed the cython, I don't get why thie problem occured, anyone can help me?

**Comment by foralliance** [comment]
@WangTianYuan 
have u solved the problem??
many many thanks!!!

**Comment by WangTianYuan** [comment]
@foralliance Is nms correct installed? You have to run `sh make.sh` first and make sure no error happens
